=== ThePotatoArchivist/rpg-server-datapack/schemas/lock_group.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "Identifier": {
      "type": "string",
      "pattern": "^[a-z0-9_.-]+:[a-z0-9/._-]+$"
    },
    "Tag": {
      "type": "string",
      "pattern": "^#[a-z0-9_.-]+:[a-z0-9/._-]+$"
    },
    "LockList": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "message": {
          "type": "string"
        },
        "entries": {
          "type": "array",
          "items": {
            "anyOf": [
              {
                "$ref": "#/definitions/Identifier"
              },
              {
                "$ref": "#/definitions/Tag"
              }
            ]
          }
        }
      },
      "required": [
        "entries"
      ]
    },
    "Requirement": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": {
        "^[a-z0-9_.-]+:[a-z0-9/._-]+$": {
          "type": "integer"
        }
      }
    }
  },
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "blocks": {
      "$ref": "#/definitions/LockList"
    },
    "entities": {
      "$ref": "#/definitions/LockList"
    },
    "item_name": {
      "type": "string"
    },
    "items": {
      "$ref": "#/definitions/LockList"
    },
    "recipes": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "message": {
          "type": "string"
        },
        "entries": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Identifier"
          }
        }
      },
      "required": [
        "entries"
      ]
    },
    "requirements": {
      "anyOf": [
        {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Requirement"
          }
        },
        {
          "$ref": "#/definitions/Requirement"
        }
      ]
    }
  },
  "required": [
    "requirements"
  ]
}

=== ThePotatoArchivist/rpg-server-datapack/data/rpgserver/rpgskills/lockgroup/_aff/7.json
{
  "requirements": {
    "rpgserver:affinity": 7
  },
  "blocks": {
    "entries": [
      "#rpgserver:wooden_racks"
    ]
  },
  
  "items": {
    "entries": [
      "minecraft:golden_hoe",
      "chipped:watering_can"
    ]
  },
  "recipes": {
    "entries": [
      "fleshz:prepared_hide"
    ]
  }
}

=== ThePotatoArchivist/rpg-server-datapack/data/rpgserver/rpgskills/lockgroup/_ing/7.json
{
  "requirements": {
    "rpgserver:ingenuity": 7
  },
  "blocks": {
    "entries": [
      "create:secondary_linear_chassis",
      "create:linear_chassis",
      "create:radial_chassis",
      "create:andesite_casing",
      "create:andesite_table_cloth",
      "create:turntable",
      "create:encased_chain_drive"
    ]
  },
  "items": {
    "entries": [
      "minecraft:hopper_minecart",
      "minecraft:furnace_minecart",
      "minecraft:chest_minecart",
      "minecraft:tnt_minecart",
      "create:secondary_linear_chassis",
      "create:linear_chassis",
      "create:radial_chassis",
      "create:andesite_casing",
      "create:andesite_table_cloth",
      "create:turntable",
      "create:encased_chain_drive"
    ]
  },
  "entities": {
    "entries": [
      "minecraft:hopper_minecart",
      "minecraft:furnace_minecart",
      "minecraft:chest_minecart",
      "minecraft:tnt_minecart"
    ]
  }
}
